In [1]:
import pandas as pd

In [11]:
orders_dt = pd.read_csv("../data/orders.csv")
con1 = orders_dt["status"] == "canceled"
con2 = orders_dt["channel"] == "app"

seg = orders_dt[con1 & con2]
seg

        order_id  customer_id       order_datetime channel    status
5         104752         1160  2024-05-22 04:30:56     app  canceled
19         38832         3389  2024-06-12 11:29:51     app  canceled
29         98881         3513  2024-06-12 12:50:48     app  canceled
48         77629         4566  2024-04-29 23:57:37     app  canceled
69        145006         1148  2024-01-09 07:26:41     app  canceled
...          ...          ...                  ...     ...       ...
199960     69097         5576  2024-05-14 12:19:50     app  canceled
199966    138569         1900  2024-04-17 14:43:23     app  canceled
199989     99142         4775  2024-05-21 09:43:50     app  canceled
199992     60874         1472  2024-04-18 13:47:11     app  canceled
199999      1963         3439  2024-01-01 00:58:02     app  canceled

[5865 rows x 5 columns]

In [13]:
segq = orders_dt.query('channel == "app" and status == "canceled"')
segq

        order_id  customer_id       order_datetime channel    status
5         104752         1160  2024-05-22 04:30:56     app  canceled
19         38832         3389  2024-06-12 11:29:51     app  canceled
29         98881         3513  2024-06-12 12:50:48     app  canceled
48         77629         4566  2024-04-29 23:57:37     app  canceled
69        145006         1148  2024-01-09 07:26:41     app  canceled
...          ...          ...                  ...     ...       ...
199960     69097         5576  2024-05-14 12:19:50     app  canceled
199966    138569         1900  2024-04-17 14:43:23     app  canceled
199989     99142         4775  2024-05-21 09:43:50     app  canceled
199992     60874         1472  2024-04-18 13:47:11     app  canceled
199999      1963         3439  2024-01-01 00:58:02     app  canceled

[5865 rows x 5 columns]

In [14]:
print(seg.shape[0], segq.shape[0], seg.shape[0] == segq.shape[0])

5865 5865 True