In [3]:
import pandas as pd

In [2]:
# pivot
df =pd.DataFrame({
    "date":["2026-01","2026-01","2026-02","2026-02"],
    "city":["seoul","busan","seoul","busan"],
    "temp":[-2.5,1.0,0.5,3.5],
    "humid":[40,55,45,60]
})
df

      date   city  temp  humid
0  2026-01  seoul  -2.5     40
1  2026-01  busan   1.0     55
2  2026-02  seoul   0.5     45
3  2026-02  busan   3.5     60

In [9]:
# 
long = df.groupby(["date","city"])[["temp","humid"]].sum()
long

df.pivot(
    columns="city",
    index="date",
    values="temp"
)

city     busan  seoul
date
2026-01    1.0   -2.5
2026-02    3.5    0.5

In [16]:
# values = multi
result = df.pivot(
    columns="city",
    index="date",
    values=["temp", "humid"]
)
result["temp"]

city     busan  seoul
date
2026-01    1.0   -2.5
2026-02    3.5    0.5

In [17]:
result["humid"]

city     busan  seoul
date
2026-01   55.0   40.0
2026-02   60.0   45.0

In [24]:
result["temp", "busan"]["2026-02"]

np.float64(3.5)

In [26]:
# melt
df = pd.DataFrame({
    "name":["hong","ko"],
    "kor":[90,80],
    "eng":[85,95],
    "grade":["A","B"]
})
df

   name  kor  eng grade
0  hong   90   85     A
1    ko   80   95     B

In [ ]:
df.melt(
    id_vars="name",
    value_vars=["kor","eng"],    # values 에 들어간 컬럼 지정
    var_name="subject"
)

   name subject  value
0  hong     kor     90
1    ko     kor     80
2  hong     eng     85
3    ko     eng     95

In [34]:
df.melt(
    id_vars=["name", "grade"],
    value_vars=["kor", "eng"],
    value_name="score",
    var_name="subject"
)

   name grade subject  score
0  hong     A     kor     90
1    ko     B     kor     80
2  hong     A     eng     85
3    ko     B     eng     95

In [ ]:
# stack : 컬럼을 인덱스로 넘겨줌
# 메소드 원형 : DataFrame.stack(lavel=-1, dropna=<no_default>, sort=True, future_stack-True)
# level 인덱스로 내릴 컬럼의 레벨. 정수, 레벨명(문자열), 또는 리스트, -1: 가장 안쪽(마지막) 레벨

In [35]:
stack_df = pd.DataFrame({
    "kor":[90,80],
    "eng":[85,85]
})
stack_df

   kor  eng
0   90   85
1   80   85

In [ ]:
stack_df.columns.name="subject"

In [39]:
stack_df.columns

Index(['kor', 'eng'], dtype='str', name='subject')

In [40]:
stack_df.index.name="name"
stack_df

subject  kor  eng
name
0         90   85
1         80   85

In [45]:
print(type(stack_df))             # stack X
print(stack_df.stack())     # stack O, (kor,eng) => index로 보냈다. column을 index로 보낸다.
print(type(stack_df.stack()))

<class 'pandas.DataFrame'>
name  subject
0     kor        90
      eng        85
1     kor        80
      eng        85
dtype: int64
<class 'pandas.Series'>

In [1]:
import numpy as np

In [ ]:
# np.arange(8)      # ndarray. list가 아님.
# np.arange(8).shape  # 1차원  (8,)
np.arange(8).reshape(2,4) # 2X4. 2차원

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
# 다중 컬럼: 특정 레벨
mi = pd.DataFrame(
    data=np.arange(8).reshape(2,4),
    index=["r1","r2"],
    columns=pd.MultiIndex.from_product(
        [["A","B"],["x","y"]],
        names=["grp","sub"]
    )
)
mi

grp  A     B
sub  x  y  x  y
r1   0  1  2  3
r2   4  5  6  7

In [6]:
# stack(MultiLevel에서). sub(column)를 index로 보냄.
mi.stack(level="sub")

grp     A  B
   sub
r1 x    0  2
   y    1  3
r2 x    4  6
   y    5  7

In [ ]:
# 모든 columns를 index로 보냄.
mi.stack(level=["grp","sub"])

    grp  sub
r1  A    x      0
         y      1
    B    x      2
         y      3
r2  A    x      4
         y      5
    B    x      6
         y      7
dtype: int64