In [10]:
import pandas as pd
# 원가 상위 5개 추출. 상품명, 카테고리, 원가

products_df = pd.read_csv("../data/products.csv")
top5_products = products_df.sort_values("cost", ascending=False).head(5)
top5_products

     product_id product_name category     price      cost
260         116       베이직 선반       가구  225800.0  165500.0
58          437    플러스 스탠드조명       가구  204100.0  148400.0
321         211       플러스 소파      가구   207100.0  143200.0
495         385       베이직 선반       가구  205900.0  130700.0
269         224      스탠다드 소파       가구  193000.0  126000.0

In [9]:
top5_products[["product_name","category","cost"]]

    product_name category      cost
260       베이직 선반       가구  165500.0
58     플러스 스탠드조명       가구  148400.0
321       플러스 소파      가구   143200.0
495       베이직 선반       가구  130700.0
269      스탠다드 소파       가구  126000.0

In [ ]:
# 원가 하위 5개 추출. 상품명, 카테고리, 원가
bottom5_products = products_df.sort_values("cost", ascending=True).head(5)
bottom5_products[["product_name", "category", "cost"]]

    product_name category    cost
443       코어 만화책       도서   400.0
121       플러스 잡지      도서    600.0
293     플러스 마스크팩       뷰티   700.0
7        프리미엄 홍차       식품   900.0
438    프리미엄 장편소설       도서  1200.0

In [ ]:
# 여러 컬럼으로 정렬, 정렬 방식도 다양하게 적용
multi_df = products_df.sort_values(
    ["category", "cost"], # 정렬할 컬럼을 지정. 1차 정렬: category, 2차 정렬: cost
    ascending=[True, False]
)
multi_df.head()

     product_id product_name category    price     cost
191         260        코어 의자       가구  34000.0  17100.0
417         174       데일리 책상       가구  53200.0  21300.0
356         360    플러스 스탠드조명       가구        0  28200.0
446         262      스탠다드 의자       가구   40900원  28200.0
468         486       베이직 소파       가구  67800.0  28800.0

In [ ]:
# 날짜 컬럼을 인덱스로 처리해서 특정 날짜 단위로 슬라이싱(범위 지정) 처리
# 주문 데이터로 처리
orders_df = pd.read_csv(
    "../data/orders.csv",
    parse_dates = ["order_datetime"]
)
orders_df.info()        # order_datetime  198067 non-null 2000개는 null

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [ ]:
# 주문 날짜 데이터 null인 행 삭제: 날짜 column을 index로. 날짜로 행 선택하려고 보냄.
orders_drop_df = orders_df.dropna(subset=["order_datetime"])    # dropna: 결측값인 행 삭제. subset은 리스트로 받으니 여러 값을 받을 수 있음.
orders_drop_df.info()

<class 'pandas.DataFrame'>
Index: 198067 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        198067 non-null  int64
 1   customer_id     198067 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         198067 non-null  str
 4   status          198067 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 11.2 MB

In [26]:
orders_drop_df.head()

   order_id  customer_id      order_datetime channel     status
0     25463         1077 2024-06-25 00:17:41   store  delivered
1    171088         2998 2024-05-28 19:35:20     web  delivered
2     27437         4066 2024-02-14 17:49:14     app  delivered
3     98425         3243 2024-05-08 16:37:36   store  delivered
4     22325         5331 2024-04-17 20:08:22     app  delivered

In [ ]:
# order_datetime을 index로 보낸다.
orders_drop_dt_df = orders_drop_df.set_index("order_datetime")
orders_drop_dt_df.head()

                     order_id  customer_id channel     status
order_datetime
2024-06-25 00:17:41     25463         1077   store  delivered
2024-05-28 19:35:20    171088         2998     web  delivered
2024-02-14 17:49:14     27437         4066     app  delivered
2024-05-08 16:37:36     98425         3243   store  delivered
2024-04-17 20:08:22     22325         5331     app  delivered

In [31]:
orders_drop_dt_sort_df = orders_drop_dt_df.sort_index()
orders_drop_dt_sort_df.head()

                     order_id  customer_id channel     status
order_datetime
2024-01-01 00:02:25     66675         2233     app    shipped
2024-01-01 00:06:11    134087         4189     web   returned
2024-01-01 00:06:55    189974         5666     web   canceled
2024-01-01 00:08:14    175545         2338     web    shipped
2024-01-01 00:08:21    163262         4291     app  delivered

In [ ]:
ord_idx = (orders_df.dropna(subset=["order_datetime"])   # DataFrame    # 결측치 제거
            .set_index("order_datetime")                 # DataFrame    # index
            .sort_index())                               # DataFrame    # sorting
ord_idx

                     order_id  customer_id channel     status
order_datetime
2024-01-01 00:02:25     66675         2233     app    shipped
2024-01-01 00:06:11    134087         4189     web   returned
2024-01-01 00:06:55    189974         5666     web   canceled
2024-01-01 00:08:14    175545         2338     web    shipped
2024-01-01 00:08:21    163262         4291     app  delivered
...                       ...          ...     ...        ...
2025-06-20 20:59:27      1371         5143     web    shipped
2025-06-22 01:52:11     76346         3088     web    shipped
2025-06-23 18:31:33    121905         5035   store  delivered
2025-06-24 21:01:13     29424         1070     web  delivered
2025-06-30 03:01:14     68743         3186     web    shipped

[198067 rows x 4 columns]

In [40]:
# 2024-06월 주문 데이터 건수
june_df = ord_idx.loc["2024-06"]    # datetime이라 가능.
june_df.shape[0]

42919

In [42]:
# 2024-06월 결측치까지 있는 주문 데이터 건수
tot_cnt = orders_df.set_index("order_datetime").sort_index().loc['2024-06'].shape[0]
tot_cnt

42919