In [8]:
import pandas as pd

# 1. orders.csv 파일에서 order_id, channel, status 추출
orders_df = pd.read_csv(
    "../data/orders.csv",
    usecols = ["order_id","channel","status"]
)
print(orders_df.head(3))
# 2. orders_sample.csv 저장, 옵션 없이 저장하면 index까지 파일에 저장됨.
# orders_df.to_csv("orders_sample.csv")    # order_id, channel, status랑 index까지 파일에 저장됨.
# index=False : 인덱스는 저장하지 마라, 그러나 인덱스를 저장해야 하는 상태가 더 많다.
orders_df.to_csv("orders_sample.csv", index=False)    # index는 저장하지 마라.

# 3. 다시 읽기
orders_sample_df = pd.read_csv('orders_sample.csv')
orders_sample_df.head(3)
# 인덱스 없으면 자동으로 부여
# 연속되는 숫자가 아니면 index=False 하면 안 됨. 자동으로 부여되어서 1,2,3 등 연속되는 숫자로 다시 부여됨.

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

In [10]:
import pandas as pd

# 1. orders.csv 파일에서 order_id, channel, status 추출
orders_df = pd.read_csv(
    "../data/orders.csv",
    usecols = ["order_id","channel","status"]
)
print(orders_df.head(3))
# 2. orders_sample.csv 저장, 옵션 없이 저장하면 index까지 파일에 저장됨.
# orders_df.to_csv("orders_sample.csv")    # order_id, channel, status랑 index까지 파일에 저장됨.
# index=False : 인덱스는 저장하지 마라, 그러나 인덱스를 저장해야 하는 상태가 더 많다.
orders_df.to_csv("orders_sample.csv", index=True)    # index=True: index는 저장해라. default.

# 3. 다시 읽기할 때 주의사항
orders_sample_df = pd.read_csv('orders_sample.csv')
orders_sample_df.head(3)
# 인덱스 없으면 자동으로 부여
# 연속되는 숫자가 아니면 index=False 하면 안 됨. 자동으로 부여되어서 1,2,3 등 연속되는 숫자로 다시 부여됨.

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

   Unnamed: 0  order_id channel     status
0           0     25463   store  delivered
1           1    171088     web  delivered
2           2     27437     app  delivered

In [13]:
# 다시 읽기 : orders_sample.csv
reload = pd.read_csv("orders_sample.csv")
print(reload.head(3))

   Unnamed: 0  order_id channel     status
0           0     25463   store  delivered
1           1    171088     web  delivered
2           2     27437     app  delivered

In [14]:
orders_df.head(3)

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered